Add docs for release-1.3
rhdhorchestrator/orchestrator-helm-operator pull request #374
Opened 2024-11-17 14:54 UTC by masayag

Signed-off-by: Moti Asayag <masayag@redhat.com>

rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED

2024-11-17 15:01 UTC, batzionb approved these changes

2024-11-18 08:04 UTC, gabriel-farache requested changes
Few links are still pointing to `main` branches instead of 1.3/release-1.3 (even if they are not yet created)

2024-11-18 08:04 UTC, gabriel-farache commented on docs/release-1.3/existing-rhdh.md
> +package: "@redhat/backstage-plugin-orchestrator@1.2.0"
do we also want to update the plugins' versions as well? They are all in 1.2

2024-11-18 08:04 UTC, gabriel-farache commented on docs/release-1.3/existing-rhdh.md
> +   1. If any service does not become available, verify the logs for that service or consult [troubleshooting steps](https://www.parodos.dev/main/docs/serverless-workflows/troubleshooting/).
`https://www.parodos.dev/main/docs/serverless-workflows/troubleshooting` should be `https://www.parodos.dev/1.3/docs/serverless-workflows/troubleshooting`

2024-11-18 08:04 UTC, gabriel-farache commented on docs/release-1.3/README.md
> +   Configure a network policy to allow traffic only between RHDH, Sonataflow services, and the workflows. The policy can be derived from [here](https://github.com/parodos-dev/orchestrator-helm-operat
Should be `https://github.com/parodos-dev/orchestrator-helm-operator/blob/release-1.3/helm-charts/orchestrator/templates/network-policies.yaml`

2024-11-18 08:04 UTC, gabriel-farache commented on docs/release-1.3/README.md
> +    oc apply -n orchestrator -f https://raw.githubusercontent.com/parodos-dev/orchestrator-helm-operator/refs/heads/main/config/samples/_v1alpha1_orchestrator.yaml
Should be `https://github.com/parodos-dev/orchestrator-helm-operator/blob/release-1.3/config/samples/_v1alpha1_orchestrator.yaml`
and 
`https://raw.githubusercontent.com/parodos-dev/orchestrator-helm-operator/refs/heads/release-1.3/config/samples/_v1alpha1_orchestrator.yaml`

2024-11-18 08:04 UTC, gabriel-farache commented on docs/release-1.3/README.md
> +    wget https://raw.githubusercontent.com/parodos-dev/orchestrator-helm-operator/main/hack/wait_for_operator_installed.sh -O /tmp/wait_for_operator_installed.sh && chmod u+x /tmp/wait_for_operator_i
Should be `https://raw.githubusercontent.com/parodos-dev/orchestrator-helm-operator/release-1.3/hack/wait_for_operator_installed.sh`

2024-11-18 08:04 UTC, gabriel-farache commented on docs/release-1.3/README.md
> +    wget https://raw.githubusercontent.com/parodos-dev/orchestrator-helm-operator/main/hack/setup.sh -O /tmp/setup.sh && chmod u+x /tmp/setup.sh
Should be `https://raw.githubusercontent.com/parodos-dev/orchestrator-helm-operator/release-1.3/hack/setup.sh`

2024-11-18 08:04 UTC, gabriel-farache commented on docs/release-1.3/README.md
> +   1. If any service does not become available, verify the logs for that service or consult [troubleshooting steps](https://www.parodos.dev/main/docs/serverless-workflows/troubleshooting/).
Should be `https://www.parodos.dev/1.3/docs/serverless-workflows/troubleshooting/`

2024-11-18 08:04 UTC, gabriel-farache commented on docs/release-1.3/README.md
> +   ensure that the default settings in the [PostgreSQL values](https://github.com/parodos-dev/orchestrator-helm-chart/blob/main/postgresql/values.yaml) file match those provided in the [Orchestrator
Should be `https://github.com/parodos-dev/orchestrator-helm-operator/blob/release-1.3/helm-charts/orchestrator/values.yaml`

2024-11-18 08:19 UTC, masayag commented on docs/release-1.3/existing-rhdh.md
> +package: "@redhat/backstage-plugin-orchestrator@1.2.0"
This is the sample, I'll update it to 1.3 once the 1.3 GA plugins are available. I'll create an issue in the meantime not to miss this.

2024-11-18 09:09 UTC, masayag commented
Thank you @gabriel-farache for a thorough review!

2024-11-18 09:10 UTC, masayag commented
@jordigilh for this PR to get merged, we need to create a `release-1.3` branch and start using it for the release instead of the main. 
We should do that before we merge https://github.com/parodos-dev/orchestrator-helm-operator/pull/247

2024-11-18 09:37 UTC, gabriel-farache approved these changes

2024-12-03 20:31 UTC, masayag commented on docs/release-1.3/existing-rhdh.md
> +package: "@redhat/backstage-plugin-orchestrator@1.2.0"
updated to 1.3.0 plugin version with their integrity values.

2024-12-03 20:37 UTC, chadcrum commented
/lgtm!

2024-12-03 20:57 UTC, merged